lancerJeu()
let btnValiderMot = document.getElementById("btnValiderMot")
console.log(btnValiderMot)
let listeBtnRadio = document.querySelectorAll(".optionSource input")
console.log(listeBtnRadio)
let inputEcriture = document.getElementById("inputEcriture")
console.log(inputEcriture)
let spanScore = document.querySelector(".zoneScore")
console.log(spanScore)
let divZoneProposition = document.querySelector(".zoneProposition")
console.log(divZoneProposition)
let listeInputRadio = document.querySelectorAll(".zoneChoix input");
console.log(listeInputRadio)
let baliseZonePropositionSpan = document.querySelector("#zoneProposition span")
console.log(baliseZonePropositionSpan)